### ISSUE TITLE
Hash/Array include matcher inconsistency (fuzzy matcher)

### ISSUE THREAD

**Issue by benjreinhart** [rspec/rspec-support#156]
I'm filing this here and not in rspec-expectations because the bug is in [fuzzy_matcher.rb#L9](https://github.com/rspec/rspec-support/blob/master/lib/rspec/support/fuzzy_matcher.rb#L9).

```ruby
RSpec.describe "Example" do
  it "should fail" do
    # fails correctly:
    expect("data" => []).to include("data" => {})

    # passes incorrectly:
    expect("data" => {}).to include("data" => [])
  end
end
```

In the expectation that incorrectly passes, the code falls through the `if` branch on line 9 and compares the two objects as if they were both arrays, although one is a hash and the other is an array. It proceeds into `arrays_match?` and since they are both empty it passes.

**Comment by myronmarston** [comment]
thanks for reporting this.  There's a fix in #157.
