### ISSUE TITLE
Suggestion: Alternate Hash differ output

### ISSUE THREAD

**Issue by hackling** [rspec/rspec-support#211]
I've have a custom matcher that I use when comparing hashes/ model objects.

The differ functionality is good, but when keys move around, especially when they aren't symbols and strings, it can sometimes be a little hard to get the information you are looking for. This becomes particularly useful when dealing with much large hashes or Rails model objects, as it only shows you the key value pairs that are incorrect, rather than all of them.

Here is an example of the current differ output and the output from my custom matcher. If there is interest in including it, I can share the rest of the code etc / potentially work on adding it as a feature.

> example_spec.rb

``` ruby
require 'spec_helper'

describe 'diff output for tags' do
  let(:hash_1) do
    {
      :akey_1 => :value_1,
      :bkey_2 => :value_2,
      :bkey_3 => :value_3,
      :bkey_4 => :value_4,
    }
  end
  let(:hash_2) do
    {
      :bkey_2 => :value_2,
      :akey_1 => :value_3,
      :akey_4 => :value_5,
      :bkey_3 => :value_3,
    }
  end

  it 'outputs using the standard differ' do
    expect(hash_1).to eq hash_2
  end

  it 'outputs using the new differ' do
    expect(hash_1).to match_hash hash_2
  end
end
```

> output.txt

```
  1) diff output for tags outputs using the standard differ
     Failure/Error: expect(hash_1).to eq hash_2

       expected: {:bkey_2=>:value_2, :akey_1=>:value_3, :akey_4=>:value_5, :bkey_3=>:value_3}
            got: {:akey_1=>:value_1, :bkey_2=>:value_2, :bkey_3=>:value_3, :bkey_4=>:value_4}

       (compared using ==)

       Diff:

       @@ -1,5 +1,5 @@
       -:akey_1 => :value_3,
       -:akey_4 => :value_5,
       +:akey_1 => :value_1,
        :bkey_2 => :value_2,
        :bkey_3 => :value_3,
       +:bkey_4 => :value_4,
     # ./spec/example_spec.rb:22:in `block (2 levels) in <top (required)>'

  2) diff output for tags outputs using the new differ
     Failure/Error: expect(hash_1).to match_hash hash_2
       key: :akey_1 expected: :value_3 got: :value_1
       key: :akey_4 expected: :value_5 got: <missing>
       key: :bkey_4 expected: <missing> got: :value_4
     # ./spec/example_spec.rb:26:in `block (2 levels) in <top (required)>'

Finished in 0.75406 seconds (files took 0.01402 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./spec/example_spec.rb:21 # diff output for tags outputs using the standard differ
rspec ./spec/example_spec.rb:25 # diff output for tags outputs using the new differ

Rerun all failed examples:

rspec ./spec/example_spec.rb:{21,25}
```

[An example with a much larger hash](https://gist.github.com/hackling/ab75162913ced90e12e4)

**Comment by myronmarston** [comment]
Interesting.  How does your differ handle large values that don't fit neatly on one line (e.g. objects with long `inspect` output or multi-line strings)?  What about when the difference is in some nested hash?

**Comment by hackling** [comment]
Sorry, I've been away on holiday.

Currently it does nothing to handle really large output. That's not to say that it couldn't be updated to do so. 
I also have an include_hash matcher as well, which is the more useful version that I use, that checks to see if the content of a smaller hash is included inside a larger one, allowing you to only check for specific key/value pairs instead against the whole hash, or slicing out a bunch of data beforehand.

**Comment by ttsui** [comment]
@hackling Is your custom matcher available anywhere? I'm encountering the same difficulty reading the builtin diff output.

**Comment by JonRowe** [comment]
I'm closing this for now as not planned due to inactivity and as part of migrating to the monorepo, we do intent to make the differ pluggable to be able to offer improved diffs in the future.
