### ISSUE TITLE
undefined method `chr' for nil:NilClass

### ISSUE THREAD

**Issue by nemski** [rspec/rspec-support#214]
I'm facing the same issue as in https://github.com/rspec/rspec-expectations/issues/316 and https://github.com/rspec/rspec-expectations/issues/573. I can fix the issue by adding and if block to check for nil values:

```ruby
if line[0].nil?
  normal(line)
else
case line[0].chr
...
```

but I'm not sure what's triggering this problem in the first place.

**Comment by myronmarston** [comment]
Can you paste your code that runs into this error?  Also, can you paste the full error message and backtrace (obtained by running the specs with `-b` to enable full backtraces)?  Finally, where did you put that code to fix the issue?

I don't have any sort of context of where or why this is happening so without these sorts of details, there's nothing I can do to help.

**Comment by JonRowe** [comment]
Can you also check which version of RSpec you're running?

**Comment by nemski** [comment]
@ddisisto can handle any replies if he wants to

**Comment by JonRowe** [comment]
Well as you can't/won't provide further information I'm closing this as stale.
