### ISSUE TITLE
Incorrect `first_non_rspec_line` in deprecation warnings if Hash#fetch is monkeypatched

### ISSUE THREAD

**Issue by tjgrathwell** [rspec/rspec-support#292]
I don't know if the right answer here is just "well, don't do that!" but this caused us some trouble today.

Consider this file (based on https://github.com/iain/verbose_hash_fetch, the actual culprit)

``` ruby
# hash_monkeypatch.rb
class Hash
  alias_method :_fetch, :fetch

  def fetch(*args, &block)
    _fetch(*args, &block)
  end
end
```

If you have a test that produces a deprecation warning, you get an inaccurate result if you loaded that monkeypatch.
### Successful Version:

``` ruby
# example1_spec.rb
def thing_raiser
  raise 'thing'
end

describe 'thing_raiser' do
  it 'raises thing' do
    expect { thing_raiser }.to raise_error
  end
end
```

> WARNING: Using the `raise_error` matcher .. .. .. Called from **/Users/tjgrathwell/workspace/rspec_stacktrace_monkeypatch_issue/spec/example_spec.rb:9**:in `block (2 levels) in <top (required)>'.
### Unsuccessful Version:

``` ruby
# example2_spec.rb
require_relative 'hash_monkeypatch'

def thing_raiser
  raise 'thing'
end

describe 'thing_raiser' do
  it 'raises thing' do
    expect { thing_raiser }.to raise_error
  end
end
```

> WARNING: Using the `raise_error` matcher .. .. .. Called from **/Users/tjgrathwell/workspace/rspec_stacktrace_monkeypatch_issue/spec/hash_monkeypatch.rb:5**:in `fetch'.
#### Commentary

The issue is that [RSpec::Support::Warnings#warn_with](https://github.com/rspec/rspec-support/blob/82ec919d89212384b9b0ab67f5d1bd88bbdefd47/lib/rspec/support/warnings.rb#L29) invokes `fetch` when fetching `first_non_rspec_line`, like so:

`call_site = options.fetch(:call_site) { CallerFilter.first_non_rspec_line }`

If `fetch` is implemented in the normal place, this isn't a problem. But if it was implemented by the user, RSpec mistakenly reports `fetch` is relevant to the deprecation.

One option would be to pass in a value for `skip_frames` to ensure the stack trace only gets scanned starting with whatever is above #warn_with itself, right now `CallerFilter.first_non_rspec_line(6)` works. But that seems brittle?

**Comment by samphippen** [comment]
Given that RSpec supports users doing things like this in other places, I think it makes sense to fix this up. @tjgrathwell do you have any interest in working up a PR to fix this problem?

**Comment by JonRowe** [comment]
You can solve this for now by filtering out the lines with: https://relishapp.com/rspec/rspec-core/v/3-4/docs/configuration/excluding-lines-from-the-backtrace I personally I think you'd be better off not monkey patching core Ruby classes :/

**Comment by myronmarston** [comment]
> I personally I think you'd be better off not monkey patching core Ruby classes

Yep.  In general, monkey patches to core types are minimally supported.  It's impossible for us to account for everything a monkey patch would do.  If users want to submit PRs to change the way we implement things to avoid some clashes with monkey patches, that's fine and we'll often merge such a PR, provided it:

* Does not increase the complexity of the code
* Does not have a negative perf impact (it's a bad tradeoff to fix things for a monkey patch used by one person but have it make RSpec slower for all users)
* Is not implemented in a brittle way

The fix you've suggested does seem brittle.  I'd worry that a refactoring could change the number of stack frames in a way that causes us to return the wrong line.

**Comment by JonRowe** [comment]
> I'd worry that a refactoring could change the number of stack frames in a way that causes us to return the wrong line.

A core concern of mine too.

**Comment by myronmarston** [comment]
Closing as we're not going to make a change here.
