### ISSUE TITLE
Performing a diff on a Rack/Rails response object recurses infinitely

### ISSUE THREAD

**Issue by imtayadeway** [rspec/rspec-support#312]
@myronmarston opening this to continue [conversation on Twitter](https://twitter.com/myronmarston/status/851582287023964160)

It appears that if you pass the response object to `PP.pp` here, it will never finish: 
https://github.com/rspec/rspec-support/blob/master/lib/rspec/support/differ.rb#L188

I doubt this is something that RSpec could/should mitigate - I'm opening this mainly to complete the investigation that began yesterday and share what I learned. Feel free to close. Of course, if you feel differently, I'm happy to attempt a fix. Thanks!

**Comment by myronmarston** [comment]
Can this be fixed upstream in rack or rails?  If their objects break `PP.pp` the probably want to know.

**Comment by imtayadeway** [comment]
> It appears that if you pass the response object to PP.pp here, it will never finish

@myronmarston I've just found that although this appears to be the case, if you wait long enough, it will eventually finish. It took about 11 minutes to finish buffering that object to stdout - I imagine that with the added overhead of going through the differ resulted in my system becoming unstable (so that it appeared that it would never finish). So...I think we could probably say this is not a bug?

**Comment by myronmarston** [comment]
Works for me.  It's unfortunate it takes that long though :(.

**Comment by imtayadeway** [comment]
> t's unfortunate it takes that long though :(.

My sentiments exactly!
