### ISSUE TITLE
Forcing full backtrace when running only one file

### ISSUE THREAD

**Issue by josecoelho** [rspec/rspec-support#327]
I usually run my specs using Guard. When saving a file, the specs auto run using the command `bundle exec rspec #{spec_path}`.

Even defining the `config.full_backtrace = false` on my `spec_helper.rb` this configuration is orvewritten by [this code](https://github.com/rspec/rspec-support/blob/111879e6451c623fdc5d8921b79f2a57d9db64f0/lib/rspec/support/spec.rb#L29) and I end up with a full backtrace.

The full backtrace forces me to scroll up the terminal and brakes the magic of the workflow.

Would be possible to keep my original configuration even when running with only one file?

**Comment by myronmarston** [comment]
> Even defining the config.full_backtrace = false on my spec_helper.rb this configuration is orvewritten by this code and I end up with a full backtrace.

The code you've referenced is common spec helper code for the spec suites of the various RSpec gems, and isn't intended to be loaded or used by end users.  Have you added a `require 'rspec/support/spec'` to your code somewhere to load it?  If not, I doubt it's being loaded and something else is probably going on.

**Comment by josecoelho** [comment]
Thank you, Myron!

It was being loaded in our `rails_helper.rb`.  Removed and problem solved! 

The magic of the BDD flow is now preserved!
