### ISSUE TITLE
Master branch miscalculates the expected argument count when a hash is passed to rest of keywords

### ISSUE THREAD

**Issue by twalpole** [rspec/rspec-support#374]
### Subject of the issue

Given an instance method on a class defined as

    def test(arg, **options) ... end

when creating a verified partial double from an instance of that class that calling it

   allow(some_object).to receive(:test)
   some_object.test('something', {})

the error `Wrong number of arguments. Expected 1, got 2` is returned which is incorrect since the empty hash is accepted by the rest of keywords `**options`

**Comment by JonRowe** [comment]
Fixed in #374
