### ISSUE TITLE
define_optimized_require_for_rspec

### ISSUE THREAD

**Issue by yb66** [rspec/rspec-support#379]
### Subject of the issue

Is there still a need for [`define_optimized_require_for_rspec`](https://github.com/rspec/rspec-support/blob/c4024e47a317d6c645b491e197cc5af13812088e/lib/rspec/support.rb#L14)? It seems to be there to handle Rubies that don't have `require_relative` but, correct me if I'm wrong, there are no longer any officially supported Rubies that do not have this method.

### Your environment
* Ruby version: Anything above v2.0.0 MRI, JRuby above 1.7 (I think), Rubinius since v2.0.0 etc
* rspec-support version: 3.8.2

### Steps to reproduce

N/A

### Expected behavior

Cut it from the code and use `require_relative` directly.

### Actual behavior

Unneeded complexity to support other libraries that have gone beyond the event horizon.

I'm happy to provide the time to do this if it looks too much like drudgery.

Regards,
iain

**Comment by JonRowe** [comment]
RSpec 3.x supports Ruby 1.8.7. So yes.

**Comment by yb66** [comment]
Thanks for the edit, it's appreciated.

I'm aware that [3.x supports 1.8.7](https://rspec.info/blog/2013/07/the-plan-for-rspec-3/#no-more-186-and-191-support) but no one is planning to yank those gems, right? If there are projects that can't upgrade Ruby, can't install backports but can upgrade RSpec, I'd love to know what they are (and how that can happen:)

If they've set the specfication correctly then the dial shouldn't go past 3.x anyway.

Just my 2 pennies. 

Regards,
iain

**Comment by JonRowe** [comment]
Sorry, just to clarify, yes this is something we could look at in RSpec 4, but we are not yet actively developing RSpec 4. So this can't be done yet.

**Comment by pirj** [comment]
@JonRowe I recall that we've decided to keep `define_optimized_require_for_rspec` for the time being.
Can we close the ticket?
