### ISSUE TITLE
With non-standard String#lines Differ raises confusing error for color diffs

### ISSUE THREAD

**Issue by mlauter** [rspec/rspec-support#390]
### Subject of the issue
I realize this is more my codebase's problem than yours, but the potential fix is quite small. For some reason the codebase I work in overrides `String#lines` to `split($/)`.

When this is the case, if you use an RSpec message expectation with args, and your expectation fails because your args don't match, and color diffing is enabled, you end up with a confusing internal error message rather than your original error message with arg diff.

```
Failures:

  1) <MyTest>
     Failure/Error: <line it failed on>

     NoMethodError:
       undefined method `chr' for nil:NilClass
```

### Your environment
* Ruby version: 2.3.8
* rspec-support version: 3.7.1

### Steps to reproduce
```
gemfile(true) do
  source "https://rubygems.org"

  gem "rspec", "3.7.0" # Activate the gem and version you are reporting the issue against.
end

puts "Ruby version is: #{RUBY_VERSION}"
require 'rspec/autorun'

class MyDependency
  def public_method(hash_arg)
    return "#{hash_arg}"
  end
end

class String
  # I know, this is terrible, but it's in the codebase I work in
  def lines
    split($/)
  end
end

class MyDummy
  attr_reader :my_dependency

  def initialize(my_dependency: nil)
    @my_dependency = my_dependency || MyDependency.new
  end

  def do_stuff
    my_dependency.public_method({a: 1, b: 2})
  end
end

RSpec.describe MyDummy do
  let(:dependency) { MyDependency.new }

  # incorrect arguments
  before { expect(dependency).to receive(:public_method).with({a: 2, b: 2}).and_return('it worked') }
  subject { MyDummy.new(my_dependency: dependency) }

  it 'works' do
    subject.do_stuff
  end
end
```

### Expected behavior
```
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Using bundler 2.0.2
Using diff-lcs 1.3
Using rspec-support 3.7.1
Using rspec-core 3.7.1
Using rspec-expectations 3.7.0
Using rspec-mocks 3.7.0
Using rspec 3.7.0
Ruby version is: 2.3.8
F

Failures:

  1) MyDummy works
     Failure/Error: my_dependency.public_method({a: 1, b: 2})

       #<MyDependency:0x00007ff56cf93508> received :public_method with unexpected arguments
         expected: ({:a=>2, :b=>2})
              got: ({:a=>1, :b=>2})
       Diff:
       @@ -1,2 +1,2 @@
       -[{:a=>2, :b=>2}]
       +[{:a=>1, :b=>2}]

     # rspec_report.rb:40:in `do_stuff'
     # rspec_report.rb:52:in `block (2 levels) in <main>'

Finished in 0.03091 seconds (files took 0.11099 seconds to load)
1 example, 1 failure

Failed examples:

rspec rspec_report.rb:51 # MyDummy works
```

### Actual behavior
```
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Using bundler 2.0.2
Using diff-lcs 1.3
Using rspec-support 3.7.1
Using rspec-mocks 3.7.0
Using rspec-core 3.7.1
Using rspec-expectations 3.7.0
Using rspec 3.7.0
Ruby version is: 2.3.8
F

Failures:

  1) MyDummy works
     Failure/Error: my_dependency.public_method({a: 1, b: 2})

     NoMethodError:
       undefined method `chr' for nil:NilClass
     # rspec_report.rb:40:in `do_stuff'
     # rspec_report.rb:52:in `block (2 levels) in <main>'

Finished in 0.02267 seconds (files took 0.08048 seconds to load)
1 example, 1 failure

Failed examples:

rspec rspec_report.rb:51 # MyDummy works
```

### Proposed fix
Adding a line to `return normal(line) if line == ''` [here](https://github.com/rspec/rspec-support/blob/master/lib/rspec/support/differ.rb#L164). I can make a PR if this is something you'd potentially be willing to merge. If not, I understand, and I can find a different solution.

**Comment by pirj** [comment]
That addition is really hard to justify.

Would it be possible for you to restore the original behaviour in `spec_helper`, and only selectively enabling that monkey patch in specs that really use `#lines`?

**Comment by JonRowe** [comment]
Hm, so typically we have operated on the policy of "we expect Ruby to be Ruby" and if you override Rubies internals that's kind of your own fault and we "won't fix", but we also provide workarounds in certain limited places where we use the original implementation of a method rather than the overridden one if we can, if we were to adopt a work around it would be of that form, where we capture the String lines method and use the original implementation of the method... 

However I'm really not sure it's worth that maintenance burden to fix one badly monkey patched implementation. I mean... this will bite you in other places...

**Comment by mlauter** [comment]
Yeah, I honestly totally agree with your assessment. It'd only make sense if it were possible for you to end up with an empty string line in that method in some other way, which it sounds like you wouldn't (assuming Ruby is Ruby). Thanks for taking the time to respond, and for your work in general. I'm a big fan of rspec.
