### ISSUE TITLE
String keys should be allowed in **kwargs

### ISSUE THREAD

**Issue by johnnymo87** [rspec/rspec-support#554]
### Subject of the issue
Ruby 2.7 introduce the feature of [last-argument non-specified keyword argument `**kwargs`](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/#other-minor-changes-non-symbol-keys) in method signatures. In this particular kind of keyword argument, String keys **_are_** allowed. But in this library's `MethodSignature` logic, we're counting on keyword arguments of any kind always being Symbol keys ([1](https://github.com/rspec/rspec-support/blob/49b89c6af0408f543c0be3772553853ec3fc9efd/lib/rspec/support/method_signature_verifier.rb#L80-L86), [2](https://github.com/rspec/rspec-support/blob/49b89c6af0408f543c0be3772553853ec3fc9efd/lib/rspec/support/method_signature_verifier.rb#L363-L378)). So in the case of `**kwargs` with String keys, we misinterpret them and treat them as intended for a positional argument.

This issue is similar to https://github.com/rspec/rspec-support/issues/522, but I believe it's not addressed by the WIP https://github.com/rspec/rspec-support/pull/537, so I figured I'd open a separate issue to highlight it.

### Your environment
* Ruby version: 3.1
* rspec-support version: 3.11

### Steps to reproduce
Run the following file:
```rb
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'rspec'
end

require 'rspec/autorun'

RSpec.configure do |config|
  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end
end

module MyModule
  def self.my_func(arg1, **kwargs); end
end

RSpec.describe MyModule do
  it 'works with kwargs with String keys' do
    expect(MyModule).to receive(:my_func).with(1, 'foo' => 'bar')

    MyModule.my_func(1, 'foo' => 'bar')
  end
end
```

### Expected behavior
The spec should pass.

### Actual behavior
Fails with the following error:
```
     Failure/Error: expect(MyModule).to receive(:my_func).with(1, 'foo' => 'bar')
       Wrong number of arguments. Expected 1, got 2.
```
Note that this passes if I change `'foo' => 'bar'` to `:foo => 'bar'`.

**Comment by JonRowe** [comment]
PR accepted to improve this

**Comment by malcolmohare** [comment]
Is the PR merged?  If so what version do I need to upgrade past to get this fix?

**Comment by JonRowe** [comment]
The previous comment was a "a pr would be accepted", no one has worked on this as far as I know

**Comment by malcolmohare** [comment]
I've submitted a PR for fixing this.  Verified the test case given in this issue passes on my branch and fails on main.

**Comment by malcolmohare** [comment]
Ok so after doing some more digging, this fix is really just reverting the changes made here https://github.com/rspec/rspec-support/pull/366, which was treating kw args differently based on whether they were symbol keys or not.  And that was done to support a specific method signature/invocation that ruby doesn't allow anymore:

```
irb(main):012:0> def foo(x = {}, y:); puts "#{x}, #{y}"; end
=> :foo
irb(main):013:0> foo 'a' => 1, y: 2
ArgumentError (unknown keyword: "a")
```

Another question I have is that ruby will happily accept pretty much anything as the hash key for a kw arg splat.  You can pass kwarg params with keys of an integer (`3 => 10`), a hash (`{"a", "b"} => 200`), whatever the rocket syntax allows.  Should this implicitly support all key types?  Or should we filter down to symbol/string as the standard hash key types?  My current PR is doing the latter.

**Comment by JonRowe** [comment]
This code is designed to seperate hash last arguments from keywords because Ruby 2.x did this, so there are parts of our verification for arguments that depend on the old behaviour. The PR you've made is a good start but the behaviour needs to be conditional based on Ruby version.
