### ISSUE TITLE
VersionChecker - check suggested version

### ISSUE THREAD

**Issue by plentz** [rspec/rspec-support#82]
quoting @myronmarston 

> One idea: we could expend the version checker to accept a minimum_version and a recommended_version. If the version being used is < the min version we'd give the user an error. If it's >= the min version but < the recommended version we'd give them a warning recommending they upgrade.
> 
> This would communicate the "upgrade to 2.3.0" message we are trying to get across without being a breaking change, and we can continue to update the recommended version as often as we want. The min version will have to stay at 2.2.0 for all RSpec 3.x releases, though.

We have two approaches to solve it:
- we can use something like `.check_suggested_version` which will be almost equal to `check_version!` but instead of raising an exception, we just log using `::Kernel.warn`. It will require two instances of `VersionChecker` if we decide to go with this approach
- add another parameter to VersionChecker constructor, but I think this will make [VersionChecker](https://github.com/rspec/rspec-support/blob/master/lib/rspec/support/version_checker.rb) more complex than it should be.

Thoughts?

related:
- https://github.com/rspec/rspec-rails/pull/1094
- https://github.com/rspec/rspec-rails/pull/1091

**Comment by benoittgt** [comment]
Is it still something we want to do? I don't see a lot of activity since 5 years, I am in favor of closing this feature request for now.

**Comment by JonRowe** [comment]
Quite out of date and with the changes to rspec-rails 4 its a less relevant, so agreed, closing.
